name: Build CUDA

on:
  push: # Triggers on every push to any branch
  pull_request:
  release:
    types: [ published ]
  workflow_dispatch: # Allows manual triggering

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  COMPILER_IMAGE: stashapp/compiler:7

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout twist3dimages/stash
      uses: actions/checkout@v2
      with:
        repository: twist3dimages/stash

    - name: Pull Latest from stashapp/stash
      run: |
        mkdir temp_dir
        git clone --depth=1 https://github.com/stashapp/stash.git temp_dir
        find temp_dir -mindepth 1 -exec mv {} . \; # Moves all files from temp_dir to the current directory
        rm -rf temp_dir  # Removes the temporary directory
      shell: /usr/bin/bash -e {0}
      env:
        COMPILER_IMAGE: stashapp/compiler:7


    - name: Prepare Dockerfile
      run: |
        ls
        rm docker/ci/x86_64/Dockerfile
        mv docker/build/x86_64/Dockerfile-Cuda docker/ci/x86_64/Dockerfile

    - name: Build Docker-CUDA Image
      run: docker build -t ghcr.io/twist3dimages/stash/stash-cuda:latest -f docker/ci/x86_64/Dockerfile .


    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker-CUDA image
      run: docker push ghcr.io/twist3dimages/stash/stash-cuda:latest
