name: Build CUDA

on:
  push: # Triggers on every push to any branch
  pull_request:
  release:
    types: [ published ]
  workflow_dispatch: # Allows manual triggering

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  COMPILER_IMAGE: stashapp/compiler:7

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout stashapp/stash
      uses: actions/checkout@v2
      with:
        repository: stashapp/stash
        # You can specify a branch, tag, or commit as needed
        ref: develop  # Replace 'main' with the branch or tag you want to checkout



    - name: Prepare Dockerfile
      run: |
        ls
        rm /docker/ci/x86_64/Dockerfile
        mv /docker/build/x86_64/Dockerfile-Cuda /docker/ci/x86_64/Dockerfile

    - name: Build Docker-CUDA Image
      run: docker build -t ghcr.io/twist3dimages/stash/stash-cuda:latest -f /docker/ci/x86_64/Dockerfile .


    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker-CUDA image
      run: docker push ghcr.io/twist3dimages/stash/stash-cuda:latest
